### ISSUE TITLE
Ошибка сегментирования

### ISSUE THREAD

**Issue by readysloth** [drkwdck/labs#2]
![image](https://user-images.githubusercontent.com/28711485/96626405-22dd3f80-1318-11eb-9cce-94f4d8a45577.png)
1. Как думаете, почему у вас произошла ошибка сегментирования? :-)) #1 
1. Если я ничего не путаю, то у вас должно было `x = -27 y = 36`
Что-то не оттуда вычли?
![image](https://user-images.githubusercontent.com/28711485/96626872-b9a9fc00-1318-11eb-85c2-7f8246fb0e54.png)

**Comment by drkwdck** [comment]
Из-за того, что забыл про стек. Сейчас добавил его очистку
![image](https://user-images.githubusercontent.com/58524213/96628183-94b68880-131a-11eb-9fe4-8084d36f39fc.png)

**Comment by drkwdck** [comment]
Насчет неправильных значений: ошибка была в строке, которую я выводил. Я там писал одни a и b, а считал с другими. Исправил это.
![image](https://user-images.githubusercontent.com/58524213/96633800-4e652780-1322-11eb-9335-2549899b2f02.png)
