### ISSUE TITLE
Вопросы к лабораторной

### ISSUE THREAD

**Issue by readysloth** [drkwdck/labs#3]
1. Чем опасно переполнение стека?
1. Зачем нужны ассемблерные модули, если пишем на высокоуровневых языках? (1-2 примера)
1. Через какие этапы проходит исходный код, чтобы превратиться в исполняемый файл?
    + На каком из них будут использованы ассемблерные модули?

Можете прикреплять картинки/ссылаться на статьи из интернета, чтобы было наглядно :)

**Comment by drkwdck** [comment]
1. Это дыра в безопасности. Так можно перезаписать адрес возврата и поломать чью-нибудь программу.

2. Мгновенная оптимизация критических для скорости обработки разделов кода, предоставление прямого доступа к оборудованию для драйверов устройств, написание кода пролога и эпилога для вызовов с атрибутом naked
Взял здесь:
https://docs.microsoft.com/ru-ru/cpp/assembler/inline/advantages-of-inline-assembly?view=vs-2019

3. Если говорить о g++:
Препроцессинг (здесь обрабатываются макросы, подключаются фалы из #include)
Компиляция (здесь полученный на прошлом шаге код преобразуется в ассемблерный)
Ассемблирование (здесь ассемблерный код преобразует полученный ранее код ассемблера в машинный код)
Компоновка(все исполняемые объектные файлы из прошлого шага и библиотеки собираются в исполняемый файл)

Загрузка (если запускаем программу) (здесь программа загружается в память)
