### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by readysloth** [drkwdck/labs#4]
+ Скажите, а в чем плюсы использования во вставках имен переменных, а не конкретных регистров?
+ Когда стоит использовать `volatile` ?

**Comment by drkwdck** [comment]
- Используя имена переменных, мы получаем уровень абстракции над регистрами. Это удобнее, так как нам не надо особо задумываться о регистрах, платформе и т.д.
- Когда в блоке `asm` находится что-то очень важное и мы не хотим, чтобы `gcc` на этапе компиляции удалил этот блок
